### ISSUE TITLE
Diskutere visning av person når man ikke har tilgang

### ISSUE THREAD

**Issue by richardborge** [navikt/modiapersonoversikt#126]
Lager en issue på dette for å kjøre teknisk diskusjon i github i stedet for å ha masse teknisk prat i jira-saken, samt at github er litt enklere å være teknisk i :)

Sakene det gjelder er OPP-429 samt OPP-421.

**Comment by richardborge** [comment]
## Problemer i front end
Det er noen problemer med front end som må løses med dette:

- Før hadde person-reduseren 2 tilstander: Person eller undefined (ikke lastet), nå får vi 3 tilstander: Person, undefined og unauthorized (kun tilgang til sikkerhetstiltak)
- Stort sett alle komponenter i visitkortet forventer en Person som objekt inn
- Person har en del obligatoriske felter, så vi kan ikke uten videre levere et tomt objekt med kun sikkerhetstiltak
- Back enden leverer nå to ulike objekter, basert på om saksbehandler har tilgang eller ikke

Det er ikke veldig smooth å fylle ut "Ikke tilgang" i alle obligatoriske felter (særlig m.t.p. at ikke alle feltene er tekst i objektet). Det er heller ikke rett frem å jobbe med ulike typer objekter inn i samme komponent.

**Comment by Quist** [comment]
Synes backend-løsningen høres fornuftig ut.

Problemer i frontend, punkt 2: Løses ved at visittkortet aldri vil bli vist hvis man ikke har tilgang.

**Comment by richardborge** [comment]
Ja, for eksempel innføre en ekstra [VisitContainerProps](https://github.com/navikt/modiapersonoversikt/blob/master/src/app/personside/visittkort/VisittkortContainer.tsx)? For eksempel 
```typescript
interface VisittContainerProps {
    IkkeTilgangTilPerson | Person | undefined
}
```
Og så rendre visittcontainer på en annen måte?

**Comment by Quist** [comment]
Kanskje så høyt oppe som mulig engentlig?

https://github.com/navikt/modiapersonoversikt/blob/master/src/app/personside/Personside.tsx
