### ISSUE TITLE
Automatisk innlogging for modiapersonoversikt

### ISSUE THREAD

**Issue by Quist** [navikt/modiapersonoversikt#144]
Vi må undersøke hvordan vi kan løse automatisk login/videresending til login-page hvis bruker ikke er logget inn.

Per i dag så er det eneste som skjer at kall til backend-failer fordi man ikke er logget inn 😢

**Comment by richardborge** [comment]
Burde vi sette opp et lite teknisk møte med Nicklas for å få en innføring i hvordan dette er gjort både med tanke på front-end og hvordan vi kobler back-end mot ABAC?

**Comment by Quist** [comment]
Ja, eller ihvertfall ta en prat med han/eller noen andre 👍

**Comment by nutgaard** [comment]
Løst ved at appen pakkes inn i ett docker-image fra PUS-gjengen som sikrer at alle er loggen inn via ISSO
