### ISSUE TITLE
Problemer med IE11 og personoversikten som NPM

### ISSUE THREAD

**Issue by richardborge** [navikt/modiapersonoversikt#210]
Legger inn original Slack-melding her først, så den ikke blir borte:

Hei folkens, vi har et lite problem rundt bygging av npm-pakker og IE11 som vi lurer på om noen av dere kan hjelpe oss med. Vi har en ny react-applikasjon som vi holder på å utvikle for å erstatte en gammel applikasjon. Det vi ønsker er å erstatte deler av den gamle applikasjoner med elementer fra den nye applikasjonen så vi får testet deler underveis og øker da muligheten for at den nye applikasjonen er vellykket når vi slipper den. Vi har derfor pakket den nye applikasjonen som en npm-pakke og dratt den inn i den gamle applikasjonen og puttet de elementene vi ønsker å teste inn der. Dette fungerte fint, men vi støtte på problemer når vi skulle prøve i IE11: Hvis vi transpilerer applikasjonen vår med ES2015 så er det funksjoner som IE11 ikke støtter (Arrow functions f.eks.). Vi må derfor transpilere med ES5, men da blir et eksternt bibliotek vi bruker tullet til fordi det virker som om transpileren ikke takler måten dette er skrevet på (uten semikolon og noe rart i regex) og da feiler både IE og Chrome. Så vi sliter litt. Den nye applikasjonen vår virker i IE11 så derfor er det så rart at når vi transpilerer så skal det bli anderledes. Og hvorfor blir eksterne bibliotek tilsynelatende transpilert på nytt når man lager et eget bibliotek.

Så rent teknisk, hva gjør vi?

1. Pakker modiapersonoversikt som en NPM, alt sammen
2. Refererer til NPM-pakken i [reactkomponenter](https://github.com/navikt/modiabrukerdialog-reactkomponenter), som er et Java-bibliotek for å dra inn react-komponenter i en JBoss applikasjon
3. Bruker reactkomponenter i [modiabrukerdialog](http://stash.devillo.no/projects/DIAL/repos/modiabrukerdialog/browse), ligger ikke på github.

Det vi har prøvd så langt er:
1. Ymse innstillinger i [tsconfig](https://github.com/navikt/modiapersonoversikt/blob/master/tsconfig.json) med ulik target og lib
2. Ymse innstillinger i [package.json](https://github.com/navikt/modiabrukerdialog-reactkomponenter/blob/master/package.json) og [babelrc](https://github.com/navikt/modiabrukerdialog-reactkomponenter/blob/master/.babelrc) i reactkomponenter, der vi har prøvd å oppgradere babel og legge til innstillinger for å støtte spesifikke browsere.

Så feilene, mer spesifikt er:
Når vi transpilerer med ES2015 i tsconfig så funker det i Chrome, men vi får feil i IE11 fordi IE11 ikke støtter arrow-functions

Når vi transpilerer med ES5 i tsconfog får vi en feil i javascriptfilen vår som knytter seg til [stylis](https://github.com/thysultan/stylis.js/blob/master/stylis.js) fordi da blir noen av regex-linjene konkatenert:
```javascript
var cursorptn = /zoo|gra/
var transformptn = /([,: ])(transform)/g
```
Bli da transpilert til:
```javascript
var cursorptn = /zoo|gra/var transformptn = /([,: ])(transform)/g
```
Stylis trekkes forøvrig inn via styled-components. Derfor er vi litt stuck.

Ekstrem nødløsning er jo å forke stylis og legge inn semikolon på linjene som feiler, men det ønsker vi ikke å gjøre.

**Comment by erlendev** [comment]
Utifra hva jeg kan se når jeg installerer `styled-components` lokalt i repo-et deres, får jeg dette i `dist`-en som de produserer:
```
var cursorptn = /zoo|gra/; /* assert cursor varient */
var transformptn = /([,: ])(transform)/g; /* vendor prefix transform, older webkit */
```

Så det ser ut for meg som at konkateneringen dere opplever i klienten er et resultat av at noe har blitt endret underveis hos dere i en eller annen byggeprosess, enten under minifying/uglifying eller transpilering, mest sannsynlig sistnevnte vil jeg tro - jeg har ikke vært borti at uglifying fjerner semikolon tidligere ihvertfall.

Fikk ikke kjørt opp appen lokalt pga. noen manglende miljøvariabler eller noe, men forstår jeg det rett som at dere bruker `create-react-app-ts`? Har ikke brukt det selv, men ville kanskje prøvd å undersøke om det kan være den som plukker opp alt av *.js (inkl det i `node_modules`) og gjør sin egen transpileringsgreie, og isåfall finne ut om dere kan forhindre det på denne depdendency'en, eller endre babel-konfigen som brukes der til å ikke fjerne semikolon.

**Comment by erlendev** [comment]
Skal sies at jeg tror neimen ikke jeg har vært borti at babel har gjort dette tidligere heller.

**Comment by eigilhs** [comment]
Viste seg at dette skyldtes minifying med wro4j i modig-frontend-wicket. Det er foreløpig slått av.
