### ISSUE TITLE
Bedre klassenavn fra styled components

### ISSUE THREAD

**Issue by winsvold** [navikt/modiapersonoversikt#25]
Denne pluginen gir oss mer beskrivende klassenavn fra styled components, samt noen andre fordeler som mulighet for server-side rendering og mindre bundle-size:
https://github.com/styled-components/babel-plugin-styled-components

Så vidt jeg skjønner tillater ikke create react app at vi setter opp egne babel-plugins uten å ejecte. Da kan denne kanskje være en alternativ løsning:
https://github.com/timarney/react-app-rewired

**Comment by Quist** [comment]
Skal vi lukke denne, @winsvold ?

**Comment by winsvold** [comment]
Prøvde å sette opp dette med [react-app-rewired](https://github.com/timarney/react-app-rewired) 

Brukte disse scriptene i package.json (som så ut til å funke fint)
```
{
  "scripts": {
    "start": "react-app-rewired start --scripts-version react-scripts-ts",
    "build": "react-app-rewired build --scripts-version react-scripts-ts",
    "test": "react-app-rewired test --scripts-version react-scripts-ts --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

Lagde en `config-overrides.js` som så ca slik ut:

```
module.exports = function override(config, env) {
  
  config = injectBabelPlugin('styled-components-babel-plugin',config)

  return config;
}
```

Ifølge det jeg skjønner er dette alt som skal til. Appen startet fint, men det så ikke ut til at babelpluginen ble brukt. Prøvde litt diverse, bla. [denne](https://github.com/withspectrum/react-app-rewire-styled-components) uten hell.

**Comment by Quist** [comment]
Tenker at dette ikke er noe veldig behov for oss, foreslår at vi lukker den @winsvold?

**Comment by winsvold** [comment]
Ser gjerne selv at vi hadde dette, hadde gjort det mye enklere å navigere i dom'en

**Comment by winsvold** [comment]
Dette ble løst med babel macro https://www.styled-components.com/docs/tooling#babel-macro i #541
