### ISSUE TITLE
Integrere nodesecurity

### ISSUE THREAD

**Issue by winsvold** [navikt/modiapersonoversikt#52]
https://nodesecurity.io/

**Comment by Quist** [comment]
Ser ut som nodesecurity ble kjøpt opp av node-folka dagen etter du posta lenken, @winsvold. Skal vi close denne?

**Comment by nutgaard** [comment]
Dere kan vurdere snyk. Tror det er lagt til på github her nå.

**Comment by Quist** [comment]
Nå som snyk er lagt til lukker jeg denne.
