### ISSUE TITLE
Lag en TestProvider

### ISSUE THREAD

**Issue by winsvold** [navikt/modiapersonoversikt#60]
Lage en ny provider som kan brukes i tester som både provider en mockstore og styled-components-theme.

**Comment by Quist** [comment]
Er denne relevant enda, @winsvold?

**Comment by winsvold** [comment]
Har laget PR på denne nå
https://github.com/navikt/modiapersonoversikt/pull/193

**Comment by winsvold** [comment]
Merget i master
